### ISSUE TITLE
What are your personal benefits of yoga?

### ISSUE THREAD

**Issue by benjmin-r** [cincuranet/ama#1]
As in: What's the thing that gives you the most when doing/practicing it?

**Comment by cincuranet** [comment]
Ashtanga yoga has defined set of asanas (split into series). So when you're doing it for a while your brain knows what's coming, what's challenging for you body etc. Yet it still needs your mind's attention and focus. Combination of these two items is what draws me into it the most.

Also I feel good, both physically and mentally when practicing, no matter whether it's for 10 minutes or 90 minutes. Maybe because of the needed attention which is so difficult to do in today's world.

And nobody is judging anybody - no matter how much I (or anybody else) practice or how advanced asanas I (or anybody else) can or can't do.
